# Generated by Django 4.0.5 on 2022-06-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
