# Generated by Django 4.0.5 on 2022-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='foods',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
